### ISSUE TITLE
frames

### ISSUE THREAD

**Issue by coachshea** [andmarti1424/scim#1]
I am a long time sc user and I love what you are doing with this project. I do have one request. It appears that all support for frames have been dropped. There were some situation in which I found frames to be very useful. I was wondering if any thought has been given to implementing this feature. Thank you for your consideration.

**Comment by andmarti1424** [comment]
This is sc-im previous repo. Please use this instead: https://github.com/andmarti1424/sc-im
Regarding your question, indeed frame support has been dropped. You can try the freeze feature though. Its not the same but it might be useful for you.
