### ISSUE TITLE
@coltoa won't take @mycol as argument

### ISSUE THREAD

**Issue by foo-bar-baz** [andmarti1424/scim#14]
it give 'Illegal numeric expression' error here.
@coltoa(A) however returns 0 as expected.
@mycol returns correct values as well.

**Comment by andmarti1424** [comment]
@coltoa receives a number representing a column and returns a string. Ex. 
You should use this function in something like: @nval(@coltoa(@mycol-1), 0).
How are you using this function??

**Comment by foo-bar-baz** [comment]
these are verbatim examples from sc's manual page:
@coltoa(@mycol-1) @nval(@coltoa(@mycol1), @myrow+1)

and i have lines like this which work in old sc but not in scim:
let F5 = @nval(@coltoa(@mycol-1),@myrow)-rent

**Comment by andmarti1424** [comment]
This example work for me..
let F5 = @nval(@coltoa(@mycol-1),@myrow)
The thing is in the rent variable!
I still have to think the best way to define and store user define variables...

**Comment by foo-bar-baz** [comment]
On Feb 07  17:05 -0800, Andr�s M. wrote:
> This example work for me..
> let F5 = @nval(@coltoa(@mycol-1),@myrow)
> The thing is in the rent variable!

true, i should've mentioned that i do have this line:

define "rent" C0
let rent = 930

works in sc but not in scim

**Comment by foo-bar-baz** [comment]
On Feb 07  17:05 -0800, Andr�s M. wrote:
> I still have to think the best way to define and store user define
> variables...

i also named columns. i don't know if it's doable with old sc. the idea is
to have a column say payment_from_x for more dynamic addressing of cells.
an example then would be:
@nval(@coltoa(payment_from_x),@myrow)

or better yet, just make nval() smart enough to figure out things without
using coltoa():
@nval(payment_from_x,@myrow)

i can open a new ticket for this if need be. just let me know.

**Comment by andmarti1424** [comment]
I close this issue since its really a 'user defined variables' issue. Please we continue this in that issue.
