### ISSUE TITLE
odd input in search '/' in help's pager

### ISSUE THREAD

**Issue by foo-bar-baz** [andmarti1424/scim#15]
strings write over each other! tested on st and systemd's console. systemd's console is similar to kmscon, basically xterm-256 with utf-8 support.

**Comment by andmarti1424** [comment]
Could you please send a printscreen to scim.spreadsheet@gmail.com ??

**Comment by andmarti1424** [comment]
Closed this by mistake.
Does this happen to you in lines that have « or » chars?

**Comment by foo-bar-baz** [comment]
On Feb 07  10:46 -0800, Andr�s M. wrote:
> Closed this by mistake.
> Does this happen to you in lines that have � or � chars?

no. so here is how i get it:
1. run scim
2. :help
3. /
4. start typing the str that i want to search for. chars get printed on the
   screen one on top of the other.

**Comment by foo-bar-baz** [comment]
On Feb 07  10:07 -0800, Andr�s M. wrote:
> Could you please send a printscreen to scim.spreadsheet@gmail.com ??

i need to record a screncast. might take a while...

**Comment by andmarti1424** [comment]
does this happen to you alsa if you type :quit ?
what is your OS?

**Comment by foo-bar-baz** [comment]
On Feb 07  16:26 -0800, Andr�s M. wrote:
> does this happen to you alsa if you type :quit ?

i'm not sure if we are talking about the same thing. typing :help is fine,
i get to help's pager. i can see the help articles. there, if i try to
search for something then i get the odd behaviour.

> what is your OS?

gentoo, amd64

**Comment by andmarti1424** [comment]
if you instead of searching something you type ":quit", do chars get printed one on top of each other?
I cannot replicate this issue.

**Comment by foo-bar-baz** [comment]
On Feb 07  19:49 -0800, Andr�s M. wrote:
> if you instead of searching something you type ":quit", do chars get
> printed one on top of each other?  I cannot replicate this issue.

same odd behaviour, so i did :q to get out. sorry, i didn't know :<command>
works in help. i used to just hit 'q' to quit.

**Comment by andmarti1424** [comment]
That makes sense since in both places I have the same getchar().. The thing is cannot replicate it!!

**Comment by foo-bar-baz** [comment]
On Feb 08  04:44 -0800, Andr�s M. wrote:
> That makes sense since in both places I have the same getchar().
>

libc perhaps? here it is glibc-2.19-r1(2.2)

> The thing is cannot replicate it!!

i just installed ffcast, i will give a try after breakfast.

**Comment by andmarti1424** [comment]
Tested in stterm and still cannot replicate it.

**Comment by foo-bar-baz** [comment]
On Feb 07  10:07 -0800, Andrés M. wrote:
> Could you please send a printscreen to scim.spreadsheet@gmail.com ??

see the attached file.

**Comment by foo-bar-baz** [comment]
On Feb 08  10:28 -0800, Andr�s M. wrote:
> Tested in stterm and still cannot replicate it.

the terminal i'm using is st too.

**Comment by andmarti1424** [comment]
I hope to get more details or someone that has this same issue. I cannot replicate it, and already tested on NetBSD, FreeBSD, Linux..
Cant see anything weird in code as well..

**Comment by andmarti1424** [comment]
Please reattach the printscreen. I do not see it here.
Thanks.

**Comment by foo-bar-baz** [comment]
On Feb 08  18:33 -0800, Andr�s M. wrote:
> Please reattach the printscreen. I do not see it here.
> Thanks.

i emailed it to the addr you gave me before. i couldn't attach it here
because it's a mkv or mp4 file.

**Comment by andmarti1424** [comment]
Would you please resend it? I did not get it. The address is: scim.spreadsheet@gmail.com
Thanks

**Comment by foo-bar-baz** [comment]
On Feb 08  18:41 -0800, Andr�s M. wrote:
> Would you please resend it? I did not get it. The address is:
> scim.spreadsheet@gmail.com Thanks

i resent it just now, please let me know when you get it.

**Comment by andmarti1424** [comment]
I believe this is the line that causes the problem:
sprintf(word_looked, "%s%c", word_looked, d);
word_looked gets blanked all the time! do not why this fails in your system and not to everyone else.

**Comment by andmarti1424** [comment]
http://busybox.net/~landley/c99-draft.html#7.19.6.6 
..." If copying takes place between objects that overlap, the behavior is undefined. "..

**Comment by andmarti1424** [comment]
What is your compiler and libc library?

**Comment by foo-bar-baz** [comment]
On Feb 09  07:29 -0800, Andrés M. wrote:
> What is your compiler and libc library?

glibc 2.19-r1(2.2)
gcc 4.8.3(4.8)

i'm attaching the build log to this as well, there is a warning
(implicit-function i think) towards the end.

i'm using gold linker (LTO) btw. 

[32;01m * [39;49;00mPackage:    app-office/scim-9999
[32;01m * [39;49;00mRepository: x-portage
[32;01m * [39;49;00mUSE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
[32;01m * [39;49;00mFEATURES:   fakeroot preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
 [32;01m*[0m Fetching git://github.com/andmarti1424/scim.git ...
git fetch git://github.com/andmarti1424/scim.git +refs/heads/dev:refs/heads/dev
git symbolic-ref refs/git-r3/app-office/scim/0/__main__ refs/heads/dev
 [32;01m*[0m Checking out git://github.com/andmarti1424/scim.git to /var/tmp/portage/app-office/scim-9999/work/scim-9999 ...
git checkout --quiet dev
GIT update -->
   repository:               git://github.com/andmarti1424/scim.git
   at the commit:            40b6db8d658e2217b59d977ce0ce1a3dd9d0e5f4
>>> Source unpacked in /var/tmp/portage/app-office/scim-9999/work
>>> Preparing source in /var/tmp/portage/app-office/scim-9999/work/scim-9999/src ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/app-office/scim-9999/work/scim-9999/src ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/app-office/scim-9999/work/scim-9999/src ...
make -j1 
yacc -d gram.y
test -f y.tab.c && mv y.tab.c gram.c
sed -f eres.sed < gram.y > experres.h
sed -f sres.sed < gram.y > statres.h
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o help.o help.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o cmds_command.o cmds_command.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o vmtbl.o vmtbl.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o undo.o undo.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o hide_show.o hide_show.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o cmds_normal.o cmds_normal.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o screen.o screen.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o lex.o lex.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o block.o block.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o cmds_insert.o cmds_insert.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o yank.o yank.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o cmds.o cmds.c
cmds.c: In function 'send_to_interp':
cmds.c:941:5: warning: implicit declaration of function 'yyparse' [-Wimplicit-function-declaration]
     (void) yyparse();
     ^
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o exec.o exec.c
exec.c: In function 'exec_cmd':
exec.c:59:18: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
             write(1, reading_buf, 1);
                  ^
exec.c:63:15: warning: ignoring return value of 'system', declared with attribute warn_unused_result [-Wunused-result]
         system("echo -n 'Press ENTER to return.'");
               ^
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\" -ffloat-store -c interp.c -o interp.o
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o xlsx.o xlsx.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o format.o format.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o file.o file.c
file.c: In function 'readfile':
file.c:450:9: warning: implicit declaration of function 'yyparse' [-Wimplicit-function-declaration]
         if (line[0] != '#') (void) yyparse();
         ^
file.c:457:16: warning: ignoring return value of 'freopen', declared with attribute warn_unused_result [-Wunused-result]
         freopen("/dev/tty", "r", stdin);
                ^
file.c: In function 'backup_file':
file.c:542:14: warning: ignoring return value of 'chown', declared with attribute warn_unused_result [-Wunused-result]
         chown(tpath, statbuf.st_uid, statbuf.st_gid);
              ^
file.c: In function 'openfile':
file.c:596:9: warning: ignoring return value of 'dup', declared with attribute warn_unused_result [-Wunused-result]
         (void) dup(pipefd[0]);           // connect to first pipe 
         ^
file.c:600:13: warning: ignoring return value of 'dup', declared with attribute warn_unused_result [-Wunused-result]
             (void) dup(pipefd[3]);       // connect to second pipe 
             ^
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o sort.o sort.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o main.o main.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o shift.o shift.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o buffer.o buffer.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o xls.o xls.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o xmalloc.o xmalloc.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o range.o range.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o cmds_visual.o cmds_visual.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o input.o input.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o color.o color.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o maps.o maps.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o conf.o conf.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o marks.o marks.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o history.o history.c
history.c: In function 'load_history':
history.c:53:22: warning: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Wunused-result]
                 fgets(linea, sizeof(linea), f);
                      ^
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o cmds_edit.o cmds_edit.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o utils/string.o utils/string.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o utils/dictionary.o utils/dictionary.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o utils/extra.o utils/extra.c
cc -DLINUX   -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DHELP_PATH=\"/usr/share/scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o gram.o gram.c
cc -Wl,-O1 -Wl,--as-needed help.o cmds_command.o vmtbl.o undo.o hide_show.o cmds_normal.o screen.o lex.o block.o cmds_insert.o yank.o cmds.o exec.o interp.o xlsx.o format.o file.o sort.o main.o shift.o buffer.o xls.o xmalloc.o range.o cmds_visual.o input.o color.o maps.o conf.o marks.o history.o cmds_edit.o utils/string.o utils/dictionary.o utils/extra.o gram.o -o scim -lm -lncurses 
>>> Source compiled.
>>> Test phase [not enabled]: app-office/scim-9999

>>> Install scim-9999 into /var/tmp/portage/app-office/scim-9999/image/ category app-office
make -j1 DESTDIR=/var/tmp/portage/app-office/scim-9999/image/ install 
install -d /var/tmp/portage/app-office/scim-9999/image//usr/bin
install scim /var/tmp/portage/app-office/scim-9999/image//usr/bin/scim
install -d /var/tmp/portage/app-office/scim-9999/image//usr/share/scim
install scim_help /var/tmp/portage/app-office/scim-9999/image//usr/share/scim/scim_help
>>> Completed installing scim-9999 into /var/tmp/portage/app-office/scim-9999/image/


 [33;01m*[0m QA Notice: Package triggers severe warnings which indicate that it
 [33;01m*[0m            may exhibit random runtime failures.
 [33;01m*[0m cmds.c:941:5: warning: implicit declaration of function 'yyparse' [-Wimplicit-function-declaration]
 [33;01m*[0m file.c:450:9: warning: implicit declaration of function 'yyparse' [-Wimplicit-function-declaration]

 [33;01m*[0m Please do not file a Gentoo bug and instead report the above QA
 [33;01m*[0m issues directly to the upstream developers of this software.
 [33;01m*[0m Homepage: https://github.com/andmarti1424/scim.git
strip: x86_64-pc-linux-gnu-strip --strip-unneeded -R .comment -R .GCC.command.line -R .note.gnu.gold-version
   usr/bin/scim
 [32;01m*[0m Removing /usr/share/info
 [32;01m*[0m Removing /usr/share/doc
 [32;01m*[39;49;00m checking 2 files for package collisions
>>> Merging app-office/scim-9999 to /
--- /usr/
--- /usr/bin/
>>> /usr/bin/scim
--- /usr/share/
--- /usr/share/scim/
>>> /usr/share/scim/scim_help
>>> Safely unmerging already-installed instance...
No package files given... Grabbing a set.
--- replaced obj /usr/share/scim/scim_help
--- replaced dir /usr/share/scim
--- replaced dir /usr/share
--- replaced obj /usr/bin/scim
--- replaced dir /usr/bin
--- replaced dir /usr
>>> Regenerating /etc/ld.so.cache...
>>> Original instance of package unmerged safely.
>>> app-office/scim-9999 merged.

**Comment by andmarti1424** [comment]
please update to dev branch and test again.

**Comment by foo-bar-baz** [comment]
On Feb 09  13:14 -0800, Andr�s M. wrote:
> please update to dev branch and test again.

fixed, thanks.

**Comment by andmarti1424** [comment]
Great! The problem was with those lines. Some compilers don't like sprintf writing and reading the same variable! I close this issue!
