### ISSUE TITLE
allow external pager for help

### ISSUE THREAD

**Issue by foo-bar-baz** [andmarti1424/scim#23]
i keep hitting 'q' to quit in help thinking it's less. could we allow for external pagers to be used in :help?

**Comment by andmarti1424** [comment]
Take note that entire documentation is in scim_help file in /src dir.
What shall we assign the 'q' key to?

**Comment by andmarti1424** [comment]
Now 'q' key quits help page. Will not allow external pager in the near future though, since I believe its not really necessary.

**Comment by foo-bar-baz** [comment]
On Feb 10  11:01 -0800, Andr�s M. wrote:
> Take note that entire documentation is in scim_help file in /src dir.
> What shall we assign the 'q' key to?

sorry, this was marked spam by gmail. i doesn't matter now, i suppose.
