### ISSUE TITLE
Backspace broken in command mode

### ISSUE THREAD

**Issue by nikisix** [andmarti1424/scim#25]
When entering a command such as ":i csv data.csv" hitting backspace does not register. 

System:
OSX 10.9.5
Terminal (default)

**Comment by andmarti1424** [comment]
Hello!! This is a terminal issue.  You can try redefining OKEY_BS macro in macros.h file with the value that your terminal generates for the Backspace key. It might generate 0x7f just like in NetBSD.
Please try that and I also ask you to give me details of the Makefile you used for building. Thanks!

**Comment by andmarti1424** [comment]
Did you managed to solve this with instructions given?

**Comment by ntomasino** [comment]
not yet andres. sorry! things were crazy at work this week (i'm still back-logged). will try your instructions in the next day or two.

**Comment by andmarti1424** [comment]
Hello! Did you managed to solve this with instructions given?

**Comment by nikisix** [comment]
Yes I did, Thanks!

the main changes were:
-prefix=/usr
+prefix=/usr/local

-#define OKEY_BS          0x107
#define OKEY_BS          0x7f//0x107

I sent you an email about two weeks ago thanking you and providing you the
exact changes that helped me, (I've included it below):


<original email>

Totally worked!
Thanks Andres
My changes are below if you're intereted. I'm running this on OSX by the
way.

index c4c302a..dca5f8d 100644

--- a/src/Makefile

+++ b/src/Makefile

@@ -12,7 +12,7 @@ SNAME := -DSNAME=\"$(name)\"

 # packaging this with an O/S, for example, you'll probably want to change

 # this to /usr.  Otherwise, /usr/local is probably more appropriate, unless

 # you're replacing the vendor-supplied version.

-prefix=/usr

+prefix=/usr/local



 # This is where the install step puts it.

 EXDIR=$(prefix)/bin

diff --git a/src/macros.h b/src/macros.h

index 5348a87..7a985e7 100644

--- a/src/macros.h

+++ b/src/macros.h

@@ -27,7 +27,7 @@

 #ifdef NETBSD

 #define OKEY_BS          0x7f

 #else

-#define OKEY_BS          0x107

+#define OKEY_BS          0x7f//0x107

 #endif

**Comment by andmarti1424** [comment]
That is good to know. I will update the WIKI later, so OSx users can take
note on this issue.
Thanks.

2015-04-06 10:51 GMT-03:00 nicki six <notifications@github.com>:

> Yes I did, Thanks!
>
> the main changes were:
> -prefix=/usr
> +prefix=/usr/local
>
> -#define OKEY_BS 0x107
> #define OKEY_BS 0x7f//0x107
>
> I sent you an email about two weeks ago thanking you and providing you the
> exact changes that helped me, (I've included it below):
>
>
> <original email>
>
> Totally worked!
> Thanks Andres
> My changes are below if you're intereted. I'm running this on OSX by the
> way.
>
> index c4c302a..dca5f8d 100644
>
> --- a/src/Makefile
>
> +++ b/src/Makefile
>
> @@ -12,7 +12,7 @@ SNAME := -DSNAME=\"$(name)\"
>
> # packaging this with an O/S, for example, you'll probably want to change
>
> # this to /usr. Otherwise, /usr/local is probably more appropriate, unless
>
> # you're replacing the vendor-supplied version.
>
> -prefix=/usr
>
> +prefix=/usr/local
>
>
>
> # This is where the install step puts it.
>
> EXDIR=$(prefix)/bin
>
> diff --git a/src/macros.h b/src/macros.h
>
> index 5348a87..7a985e7 100644
>
> --- a/src/macros.h
>
> +++ b/src/macros.h
>
> @@ -27,7 +27,7 @@
>
> #ifdef NETBSD
>
> #define OKEY_BS 0x7f
>
> #else
>
> -#define OKEY_BS 0x107
>
> +#define OKEY_BS 0x7f//0x107
>
> #endif
>
> On Mon, Apr 6, 2015 at 7:46 AM, Andrés M. <notifications@github.com>
> wrote:
>
> > Hello! Did you managed to solve this with instructions given?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/andmarti1424/scim/issues/25#issuecomment-90047281>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andmarti1424/scim/issues/25#issuecomment-90071082>.
>



-- 
Andrés Martinelli

**Comment by nikisix** [comment]
Glad I could be of service :)

**Comment by andmarti1424** [comment]
Hello. I am planning on adding an OSX flag in Makefile, so there will be no need to change the macro OKEY_BS in macros.h file.

Do you remember if you set the Linux flag?
LINUX := -DLINUX

Or perhaps the FREEBSD or NETBSD?

Thanks!

**Comment by nikisix** [comment]
hi,
 i didn't mess with any of the linux, freebsd, or netbsd flags. if you'd
like me to look into something i'd be happy to.

ps. check out my new program btw
https://github.com/nikisix/ff
cheers!
