### ISSUE TITLE
Using mark and copy with a range

### ISSUE THREAD

**Issue by kmandla** [andmarti1424/scim#26]
Hello. I'm enjoying scim immensely; it's a huge improvement over the traditional sc.

I have question that may be a bug, or may be a feature request -- I'm not sure.

I use the "m" and letter key to mark a cell, and "c" and letter key to copy the contents, as in the old sc.

However it seems if I select a range of cells, with "R" then "x" and "y" or whichever letter sequence, the same behavior isn't available. 

In other words, I want to select a range, then mark it, then copy it in the same fashion as the old "m" and "c" keys. I can "yank" that range and "paste" in vim style, but that doesn't preserve formulas in the same fashion.

Am I overlooking that feature? or is it not working right? I've tried as many combinations of keypresses as I could think of, but I don't see if it's possible.

Thanks again, and please keep up the good work. scim is a wonderful program.

**Comment by andmarti1424** [comment]
Hello! Id rather say is a different program than and improvement, but thanks!
If you want to preserve formulas you can may be use the 'Pc' command ??
Did you try it?

**Comment by kmandla** [comment]
I will try that -- thank you! Please keep up the good work! :)

**Comment by andmarti1424** [comment]
Your comment let me find a bug. I fixed it and added the same behavior as with the Pc command, but using the 'c' command.
Just uploaded it to the dev branch.
