### ISSUE TITLE
Undo does not undo 'copies'

### ISSUE THREAD

**Issue by Miesco** [andmarti1424/scim#27]
Thanks so much for making this andmarti1424; great program!

If I type 'ma', then paste it with 'ca', then hit 'u'.  It says "No undo's left."

**Comment by andmarti1424** [comment]
Hello and thanks for testing/using this program.
I guess you are right. the 'c' command is not saving in the undo struct.
May be it was too late and/or may be it was the second scotch...
I can fix that, but...
The main issue, and the most important I have to solve is the undo of
actions that changes references..
Ex. You have @sum(A10:B15) in a C0, and insert a row above the first row,
and then undo the last action.. The reference is not recovered correctly.
This change will involve a change in how chained references are saved..


2015-06-18 19:24 GMT-03:00 Miesco <notifications@github.com>:

> Thanks so much for making this andmarti1424; great program!
>
> If I type 'ma', then paste it with 'ca', then hit 'u'. It says "No undo's
> left."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andmarti1424/scim/issues/27>.
>



-- 
Andrés Martinelli

**Comment by andmarti1424** [comment]
Uploaded fix to dev branch. Please try it and report back! Thanks.

**Comment by andmarti1424** [comment]
Could you try the fix in the dev branch?
