### ISSUE TITLE
Can not visually select a range while typing a function

### ISSUE THREAD

**Issue by Miesco** [andmarti1424/scim#28]
I type =@sum(\<tab> in 'sc' and it allows me to select a range visually.  In 'scim', \<tab> just enters ESC mode.

Is this a design decision?

PS: I realize you can visually select a range, add it to mark 'a', then type =@sum(\<c-r>a).

**Comment by andmarti1424** [comment]
Hello. Indeed, that's not possible in SCIM. Maybe we can add it in future though.
