### ISSUE TITLE
Name clashes with existing software/packages

### ISSUE THREAD

**Issue by JoopClaireIT** [andmarti1424/scim#30]
scim is also the name of an input method framework, which is still packaged in most linux systems.

**Comment by JoopClaireIT** [comment]
Proposed other names:

- spim
- sim
- scimp
- spreaded
- sc-im
- spreadsheet

**Comment by andmarti1424** [comment]
Hello. Yes, I am aware of that, as I already mentioned in some forums.
However, this program is not in available in any distro / package manager, and probably never will.
People who download it will probably will find it anyway just by "scim spreadsheet"..

**Comment by JoopClaireIT** [comment]
I would love to see it packaged though, and in fact I can imagine myself
doing that for arch...

Op vr 17 jul. 2015 14:57 schreef Andrés M. <notifications@github.com>:

> Closed #30 <https://github.com/andmarti1424/scim/issues/30>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andmarti1424/scim/issues/30#event-358468574>.
>
-- 
Met vriendelijke groet,
Joop Kiefte

Claire Automotive Support - Boekdrukker 1 - 3861SE - NIJKERK
Tel 085 0020 211 - www.claireit.nl

**Comment by ids1024** [comment]
Another possible name would be sc-ng, which does not appear to be taken and makes it's purpose clear to someone who knows what sc is.

**Comment by andmarti1424** [comment]
Actually, I liked sc-im, because it keeps the same letters and sounds the same..
