### ISSUE TITLE
sk/sh

### ISSUE THREAD

**Issue by reckbo** [andmarti1424/scim#31]
When I use the shift left or shift up commands they delete the cell.  But shift right and shift down
work as I expect (shifting the contents).  Am I misunderstanding something?

**Comment by andmarti1424** [comment]
Hello!
Shift left and up do delete cell contents.
Just like in other spreadsheet programs.

2015-08-19 10:02 GMT-03:00 reckbo <notifications@github.com>:

> When I use the shift left or shift up commands they delete the cell. But
> shift right and shift down
> work as I expect (shifting the contents). Am I misunderstanding something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andmarti1424/scim/issues/31>.
>



-- 
Andrés Martinelli

**Comment by reckbo** [comment]
Thanks!
Ryan
